### ISSUE TITLE
RegistrationJFrame: Special Characters

### ISSUE THREAD

**Issue by DigitalCoffee** [devinc13/SENG426ECheque#1]
Defect: Error message was shown when adding special characters to the input fields but only said “~!@#$%^&”

Restricted input fields. Text fields will only accepts text, number fields will only accept numbers, and the IP address field only accepts a certain format

Solution: Add descriptive error message

**Comment by kahunalu** [comment]
![Seems to be having trouble in master](https://cloud.githubusercontent.com/assets/7245192/17116884/a0f5dc3e-526e-11e6-917b-e50d4c5c4d76.PNG)

**Comment by devinc13** [comment]
Regexes updated.
